@host = http://localhost:4000/das/v1

###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "username":"Prueba",
    "password":"admin"
}

###
POST {{host}}/curriculums
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "uuidPerson": "11fab448-9bae-4b35-adce-ccf3a3edbb16",
    "direction": "4Ta Calle 3",
    "country": "Jalapa",
    "homePhone":"79223564",
    "bornPlace":"Jalapa",
    "nacionality":"Guatemalteco",
    "municipality":"Jalapaneco",
    "village":"Jalapa",
    "workPhone":"41806704",
    "age":"18",
    "civilStatus":"Casado",
    "etnia":"Ladino",
    "passport":"123456",
    "license":"123"
    }

###
GET {{host}}/curriculums/11fab448-9bae-4b35-adce-ccf3a3edbb16
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
PUT {{host}}/curriculums/18214f84-f835-4cd0-a2ef-717c9429de08
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "direction": "Monjas",
    "country": "Monjas",
    "homePhone":"41806704",
    "bornPlace":"Monjas",
    "nacionality":"Mexicano",
    "municipality":"Monjeño",
    "village":"Monjas",
    "workPhone":"79220034",
    "age":"19",
    "civilStatus":"Soltero",
    "etnia":"Ladino",
    "passport":"654321",
    "license":"321"
    }
###
GET {{host}}/requestvacations/alo/hola
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/references/refFam
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "uuidPerson": "18214f84-f835-4cd0-a2ef-717c9429de08",
    "name": "Donal",
    "phone": "41806704",
    "relationship":"Hermano",
    "bornDate": "2001-06-17",
    "isFamiliar": true
    }


###
GET {{host}}/references/refFam/18214f84-f835-4cd0-a2ef-717c9429de08
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/references/refPer/18214f84-f835-4cd0-a2ef-717c9429de08
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/personEducation
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "uuidPerson": "18214f84-f835-4cd0-a2ef-717c9429de08",
    "country": "Jalapa",
    "establishment": "Ni idea",
    "periodOf":"2001-06-17",
    "periodTo": "2001-06-17",
    "certificate":"No se que va aqui",
    "status":"Aqui peor",
    "grade": "Toy graduado"
    }


###
GET  {{host}}/personEducation/18214f84-f835-4cd0-a2ef-717c9429de08
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/workExp
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "uuidPerson": "18214f84-f835-4cd0-a2ef-717c9429de08",
    "direction": "Jalapa, Jalapa",
    "phone": "41806704",
    "reason":"Hueva",
    "dateof": "2001-06-17",
    "dateto":"2001-06-17",
    "job":"Catador",
    "bossName": "Henry",
    "sector": "Compu",
    "salary": 1250.20,
    "workexpcol": "Ni idea"
    }


###
GET {{host}}/workExp/18214f84-f835-4cd0-a2ef-717c9429de08
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}