@host = http://localhost:4000/das/v1

###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "username":"Prueba",
    "password":"admin"
}

###
POST {{host}}/permission
Authorization: Bearer {{login.response.body.token}}
Date: {{$datetime iso8601}}
Content-Type: application/json

{
    "permissionDate": "2022-05-05",
    "uuidPerson": "9fa7476a-a00a-45e1-ae26-17bb4114c521",
    "bossOne": "01766969-21e5-4ea2-b392-f410508deae0",
    "bossTwo": "01766969-21e5-4ea2-b392-f410508deae0",
    "motive": "Asueto por cumpleaños",
    "document": "hola"
}


###
GET {{host}}/permission?startdate=2021/02/05&enddate=2023/02/27
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/information/bossone
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/table/bossone/9fa7476a-a00a-45e1-ae26-17bb4114c521
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/table/bosstwo/c6b295c3-dc12-41f9-b45c-76c609bbd23e
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/table/useractive/c6b295c3-dc12-41f9-b45c-76c609bbd23e
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/table/user/c6b295c3-dc12-41f9-b45c-76c609bbd23e
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/information/bosstwo
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/271a64c5-7b0a-47f5-9daf-99a937887c4c
Authorization: Bearer {{login.response.body.token}}

###
PUT {{host}}/permission/2046b611-3506-49bf-aa88-87f92f5a2783
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "statusBossTwo": "Aceptada"
}
