@host = http://localhost:4000/das/v1

###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "username":"Prueba",
    "password":"admin"
}

###
POST {{host}}/permission
Authorization: Bearer {{login.response.body.token}}
Date: {{$datetime iso8601}}
Content-Type: application/json

{
    "permissionDate": "2022-05-05",
    "uuidPerson": "001490e6-e5b7-48bb-8387-7f63c19cf604",
    "bossOne": "00464850-7676-4884-a19d-2d338269aefd",
    "bossTwo": "00464850-7676-4884-a19d-2d338269aefd",
    "motive": "No se"
}

###
GET {{host}}/permission
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/information/bossone
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/information/bosstwo
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/permission/9429092c-9814-40dc-ad06-b511961db4ad
Authorization: Bearer {{login.response.body.token}}

###
PUT {{host}}/permission/5b41f372-bb7e-4f08-b251-3f87b1b5260f
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "last_vacation_from": "2021-05-12",
    "last_vacation_to": "2021-05-12",
    "vacation_from_date": "2021-05-12",
    "vacation_to_date": "2021-05-12",
    "has_vacation_day": false,
    "days_quantity": 0,
    "observations": "Esta es una observación",
    "person_server": {
      "uuid": "F34DBCD1-E61A-42E7-9D8C-965E4B5EA086"
    }
}
