 @host = http://localhost:4000/das/v1
#@host =  https://das-jalapa-system.herokuapp.com/das/v1

###
POST {{host}}/users/register
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "username":"mynor",
    "password":"mynor",
    "id_rol": 2,
    "uuidPerson": "18214f84-f835-4cd0-a2ef-717c9429de08"
}

###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "username":"Prueba",
    "password":"admin"
}

###

PUT {{host}}/users/a00cfe0c-1cc1-4aff-9513-3034ee63e54a
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "id_rol" : 1,
    "username": "PruebaTobar"
}

###
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}


###
POST {{host}}/users/changepassword
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "actual_password":"123456",
    "new_password":"abcde"
}

