 @host = http://localhost:4000/das/v1
#@host =  https://das-jalapa-system.herokuapp.com/das/v1

###
POST {{host}}/users/register
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "username":"mynor",
    "password":"mynor",
    "id_rol": 2,
    "uuidPerson": "18214f84-f835-4cd0-a2ef-717c9429de08"
}

###
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "username":"segundaprueba",
    "password":"admin"
}

###

PUT {{host}}/users/c1a683ff-100d-4500-af3b-01921e7bbe31
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "id_rol" : 1,
    "username": "Prueba",
    "password":"admin"
}

###
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/employees
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/bosses
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/users/a00cfe0c-1cc1-4aff-9513-3034ee63e54a
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/users/changepassword
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "actual_password":"123456",
    "new_password":"abcde"
}


###

DELETE {{host}}/users/c298138b-7a64-46dc-a00b-b517314b9727
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

